# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/source/bot_management.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BotManagement(object):
    def setupUi(self, BotManagement):
        BotManagement.setObjectName("BotManagement")
        BotManagement.resize(800, 600)
        self.exit_to_menu = QtWidgets.QPushButton(BotManagement)
        self.exit_to_menu.setGeometry(QtCore.QRect(12, 557, 271, 31))
        self.exit_to_menu.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.exit_to_menu.setObjectName("exit_to_menu")
        self.statistics_box = QtWidgets.QGroupBox(BotManagement)
        self.statistics_box.setGeometry(QtCore.QRect(295, 9, 491, 581))
        self.statistics_box.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.statistics_box.setAlignment(QtCore.Qt.AlignCenter)
        self.statistics_box.setObjectName("statistics_box")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.statistics_box)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 466, 185))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(85, 0))
        self.label_2.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_2.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_6.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_4.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_3.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_6.addWidget(self.lineEdit_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_5.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.information_box = QtWidgets.QGroupBox(BotManagement)
        self.information_box.setGeometry(QtCore.QRect(15, 10, 266, 541))
        self.information_box.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.information_box.setAlignment(QtCore.Qt.AlignCenter)
        self.information_box.setObjectName("information_box")
        self.pushButton_2 = QtWidgets.QPushButton(self.information_box)
        self.pushButton_2.setGeometry(QtCore.QRect(15, 30, 236, 36))
        self.pushButton_2.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.information_box)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(15, 75, 236, 56))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_5.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_7.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_7.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_7.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.information_box)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(15, 135, 236, 56))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_6.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_8.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_8.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_8.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_7.addWidget(self.pushButton_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.information_box)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(15, 205, 236, 96))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_9.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 2, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_10.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 0, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)

        self.retranslateUi(BotManagement)
        QtCore.QMetaObject.connectSlotsByName(BotManagement)

    def retranslateUi(self, BotManagement):
        _translate = QtCore.QCoreApplication.translate
        BotManagement.setWindowTitle(_translate("BotManagement", "Form"))
        self.exit_to_menu.setText(_translate("BotManagement", "Выйти в меню"))
        self.statistics_box.setTitle(_translate("BotManagement", "Статистика"))
        self.label.setText(_translate("BotManagement", "Никнейм бота:"))
        self.pushButton.setText(_translate("BotManagement", "Обновить"))
        self.label_2.setText(_translate("BotManagement", "Статус бота:"))
        self.comboBox.setItemText(0, _translate("BotManagement", "В сети"))
        self.comboBox.setItemText(1, _translate("BotManagement", "Не активный"))
        self.comboBox.setItemText(2, _translate("BotManagement", "Не беспокоить"))
        self.comboBox.setItemText(3, _translate("BotManagement", "Не в сети"))
        self.pushButton_6.setText(_translate("BotManagement", "Обновить"))
        self.label_3.setText(_translate("BotManagement", "Пользовательский статус бота:"))
        self.pushButton_4.setText(_translate("BotManagement", "Обновить"))
        self.label_4.setText(_translate("BotManagement", "Количество серверов:"))
        self.pushButton_3.setText(_translate("BotManagement", "Обновить"))
        self.label_5.setText(_translate("BotManagement", "Количество пользователей:"))
        self.pushButton_5.setText(_translate("BotManagement", "Обновить"))
        self.information_box.setTitle(_translate("BotManagement", "Информация"))
        self.pushButton_2.setText(_translate("BotManagement", "Скрыть информацию"))
        self.label_6.setText(_translate("BotManagement", "Название бота:"))
        self.pushButton_7.setText(_translate("BotManagement", "+"))
        self.label_7.setText(_translate("BotManagement", "Токен бота:"))
        self.pushButton_8.setText(_translate("BotManagement", "+"))
        self.label_8.setText(_translate("BotManagement", "Команды"))
        self.pushButton_9.setText(_translate("BotManagement", "Отключить"))
        self.pushButton_10.setText(_translate("BotManagement", "Подключить"))
