from PyQt5 import QtCore, QtGui, QtWidgets, Qt


class ManagementBot(QtWidgets.QWidget):
    def __init__(self, parent=None):
        QtWidgets.QWidget.__init__(self, parent=parent)

        self.create_elements()
        self.customize_elements()
        self.add_layouts()
    
    def create_elements(self):
        self.statistic_box = QtWidgets.QGroupBox(self)
        self.statistic_box.setGeometry(QtCore.QRect(285, 10, 501, 576))
        self.statistic_box.setAlignment(QtCore.Qt.AlignCenter)

        self.horizontal_layout_widget = QtWidgets.QWidget(self.statistic_box)
        self.horizontal_layout_widget.setGeometry(QtCore.QRect(20, 25, 466, 27))
        self.nick_label = QtWidgets.QLabel(self.horizontal_layout_widget)
        self.nick_line = QtWidgets.QLineEdit(self.horizontal_layout_widget)
        self.nick_line.setReadOnly(True)
        self.nick_update_button = QtWidgets.QPushButton(self.horizontal_layout_widget)

        self.horizontal_layout_widget2 = QtWidgets.QWidget(self.statistic_box)
        self.horizontal_layout_widget2.setGeometry(QtCore.QRect(20, 70, 361, 31))
        self.status_label = QtWidgets.QLabel(self.horizontal_layout_widget2)
        self.select_status = QtWidgets.QComboBox(self.horizontal_layout_widget2)
        self.update_status = QtWidgets.QPushButton(self.horizontal_layout_widget2)
        
        self.horizontal_layout_widget3 = QtWidgets.QWidget(self.statistic_box)
        self.horizontal_layout_widget3.setGeometry(QtCore.QRect(20, 185, 351, 36))
        self.count_guilds_label = QtWidgets.QLabel(self.horizontal_layout_widget3)
        self.count_guilds_line = QtWidgets.QLineEdit(self.horizontal_layout_widget3)
        self.count_guilds_line.setReadOnly(True)
        self.update_count_guilds = QtWidgets.QPushButton(self.horizontal_layout_widget3)

        self.horizontal_layout_widget4 = QtWidgets.QWidget(self.statistic_box)
        self.horizontal_layout_widget4.setGeometry(QtCore.QRect(20, 275, 466, 31))

        self.horizontal_layout_widget5 = QtWidgets.QWidget(self.statistic_box)
        self.horizontal_layout_widget5.setGeometry(QtCore.QRect(20, 240, 466, 31))

        self.grid_layout_widget = QtWidgets.QWidget(self.statistic_box)
        self.grid_layout_widget.setGeometry(QtCore.QRect(20, 120, 351, 55))
        self.user_status_label = QtWidgets.QLabel(self.grid_layout_widget)
        self.user_status_line = QtWidgets.QLineEdit(self.grid_layout_widget)
        self.update_user_status = QtWidgets.QPushButton(self.grid_layout_widget)
        
        self.information_box = QtWidgets.QGroupBox(self)
        self.information_box.setGeometry(QtCore.QRect(10, 10, 251, 541))
        self.information_box.setAlignment(QtCore.Qt.AlignCenter)

        self.show_or_hide = QtWidgets.QPushButton(self.information_box)
        self.show_or_hide.setGeometry(QtCore.QRect(15, 30, 221, 31))

        self.vertical_layout = QtWidgets.QWidget(self.information_box)
        self.vertical_layout.setGeometry(QtCore.QRect(15, 72, 219, 100))
        self.top_show_or_hide = QtWidgets.QPushButton(self.vertical_layout)
        self.top_show_or_hide.setMaximumSize(QtCore.QSize(26, 26))
        self.top_name_line = QtWidgets.QLineEdit(self.vertical_layout)
        self.top_name_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.top_name_line.setReadOnly(True)
        self.top_name_label = QtWidgets.QLabel(self.vertical_layout)
        self.top_name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.middle_token_line = QtWidgets.QLineEdit(self.vertical_layout)
        self.middle_token_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.middle_token_line.setReadOnly(True)
        self.middle_show_or_hide = QtWidgets.QPushButton(self.vertical_layout)
        self.middle_show_or_hide.setMaximumSize(QtCore.QSize(26, 26))
        self.middle_token_label = QtWidgets.QLabel(self.vertical_layout)
        
        self.vertical_layout2 = QtWidgets.QWidget(self.information_box)
        self.vertical_layout2.setGeometry(QtCore.QRect(15, 210, 219, 88))
        self.cogs_label = QtWidgets.QLabel(self.vertical_layout2)
        self.cogs_label.setMaximumSize(QtCore.QSize(300, 25))
        self.cogs_label.setAlignment(QtCore.Qt.AlignCenter)
        self.off_cogs = QtWidgets.QComboBox(self.vertical_layout2)
        self.off_cogs.setMaximumSize(QtCore.QSize(104, 28))
        self.disconnect = QtWidgets.QPushButton(self.vertical_layout2)
        self.connect = QtWidgets.QPushButton(self.vertical_layout2)
        self.on_cogs = QtWidgets.QComboBox(self.vertical_layout2)
        self.on_cogs.setMaximumSize(QtCore.QSize(104, 28))
        
        self.exit_button = QtWidgets.QPushButton(self)
        self.exit_button.setGeometry(QtCore.QRect(10, 555, 251, 31))  

    def customize_elements(self):
        self.statistic_box.setStyleSheet("font: 10pt \"Arial\";")
        self.nick_label.setStyleSheet("font: 10pt \"Arial\";")
        self.nick_update_button.setStyleSheet("font: 8pt \"Arial\";")
        self.nick_line.setStyleSheet("font: 8pt \"Arial\";")
        self.status_label.setStyleSheet("font: 10pt \"Arial\";")
        self.select_status.setStyleSheet("font: 9pt \"Arial\";")
        self.update_status.setStyleSheet("font: 8pt \"Arial\";")
        self.user_status_label.setStyleSheet("font: 10pt \"Arial\";")
        self.user_status_line.setStyleSheet("font: 8pt \"Arial\";")
        self.update_user_status.setStyleSheet("font: 8pt \"Arial\";")
        self.count_guilds_label.setStyleSheet("font: 10pt \"Arial\";")
        self.count_guilds_line.setStyleSheet("font: 8pt \"Arial\";")
        self.update_count_guilds.setStyleSheet("font: 8pt \"Arial\";")
        self.information_box.setStyleSheet("font: 10pt \"Arial\";")
        self.show_or_hide.setStyleSheet("font: 10pt \"Arial\";")
        self.top_name_label.setStyleSheet("font: 10pt \"Arial\";")
        self.middle_token_label.setStyleSheet("font: 10pt \"Arial\";")
        self.cogs_label.setStyleSheet("font: 10pt \"Arial\";")
        self.disconnect.setStyleSheet("font: 9pt \"Arial\";")
        self.connect.setStyleSheet("font: 9pt \"Arial\";")
        self.exit_button.setStyleSheet("font: 10pt \"Arial\";")
        self.top_name_line.setStyleSheet("font: 9pt \"Arial\";")
        self.middle_token_line.setStyleSheet("font: 9pt \"Arial\";")

        self.top_show_or_hide.setText("+")
        self.middle_show_or_hide.setText("+")

        self.statistic_box.setTitle("СТАТИСТИКА")
        self.nick_label.setText("Никнейм бота:")
        self.nick_update_button.setText('Обновить')
        self.status_label.setText("Статус бота:")
        self.update_status.setText("Обновить")
        self.user_status_label.setText("Пользовательский статус бота:")
        self.update_user_status.setText("Обновить")
        self.count_guilds_label.setText("Количество серверов:")
        self.update_count_guilds.setText("Обновить")
        self.information_box.setTitle("ИНФОРМАЦИЯ")
        self.show_or_hide.setText("Скрыть информацию")
        self.top_name_label.setText("Название бота:")
        self.middle_token_label.setText("Токен бота:")
        self.cogs_label.setText("Комманды:")
        self.disconnect.setText("Отключить")
        self.connect.setText("Подключить")
        self.exit_button.setText("Выйти в меню")

        self.select_status.addItem("В сети")
        self.select_status.addItem("Не активный")
        self.select_status.addItem("Не беспокоить")
        self.select_status.addItem("Не в сети")
        
    def add_layouts(self):
        self.nick_layout = QtWidgets.QHBoxLayout(self.horizontal_layout_widget)
        self.nick_layout.setContentsMargins(0, 0, 0, 0)
        self.status_layout = QtWidgets.QHBoxLayout(self.horizontal_layout_widget2)
        self.status_layout.setContentsMargins(0, 0, 0, 0)
        self.count_guilds_layout = QtWidgets.QHBoxLayout(self.horizontal_layout_widget3)
        self.count_guilds_layout.setContentsMargins(0, 0, 0, 0)
        self.user_status_layout = QtWidgets.QGridLayout(self.grid_layout_widget)
        self.user_status_layout.setContentsMargins(0, 0, 0, 0)
        self.bot_information_layout = QtWidgets.QVBoxLayout(self.vertical_layout)
        self.bot_information_layout.setContentsMargins(0, 0, 0, 0)
        self.cogs_layout = QtWidgets.QVBoxLayout(self.vertical_layout2)
        self.cogs_layout.setContentsMargins(0, 0, 0, 0)
        self.top_layout = QtWidgets.QGridLayout()
        self.middle_layout = QtWidgets.QGridLayout()
        self.management_cogs_layout = QtWidgets.QGridLayout()

        self.nick_layout.addWidget(self.nick_label)
        self.nick_layout.addWidget(self.nick_line)
        self.nick_layout.addWidget(self.nick_update_button)
        self.status_layout.addWidget(self.status_label)
        self.status_layout.addWidget(self.select_status)
        self.status_layout.addWidget(self.update_status)
        self.user_status_layout.addWidget(self.user_status_line, 1, 0, 1, 1)
        self.user_status_layout.addWidget(self.user_status_label, 0, 0, 1, 1)
        self.user_status_layout.addWidget(self.update_user_status, 1, 1, 1, 1)
        self.count_guilds_layout.addWidget(self.count_guilds_label)
        self.count_guilds_layout.addWidget(self.count_guilds_line)
        self.count_guilds_layout.addWidget(self.update_count_guilds)
        self.top_layout.addWidget(self.top_show_or_hide, 1, 2, 1, 1)
        self.top_layout.addWidget(self.top_name_line, 1, 1, 1, 1)
        self.top_layout.addWidget(self.top_name_label, 0, 1, 1, 1)
        self.middle_layout.addWidget(self.middle_token_line, 1, 0, 1, 1)
        self.middle_layout.addWidget(self.middle_show_or_hide, 1, 1, 1, 1)
        self.middle_layout.addWidget(self.middle_token_label, 0, 0, 1, 1)
        self.cogs_layout.addWidget(self.cogs_label)
        self.management_cogs_layout.addWidget(self.off_cogs, 3, 2, 1, 1)
        self.management_cogs_layout.addWidget(self.disconnect, 2, 0, 1, 1)
        self.management_cogs_layout.addWidget(self.connect, 2, 2, 1, 1)
        self.management_cogs_layout.addWidget(self.on_cogs, 3, 0, 1, 1)

        self.bot_information_layout.addLayout(self.top_layout)
        self.bot_information_layout.addLayout(self.middle_layout)
        self.cogs_layout.addLayout(self.management_cogs_layout)
