# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManagementBot.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManagementWidget(object):
    def setupUi(self, ManagementWidget):
        ManagementWidget.setObjectName("ManagementWidget")
        ManagementWidget.resize(800, 1011)
        ManagementWidget.setStyleSheet("\n"
"")
        self.statistic_box = QtWidgets.QGroupBox(ManagementWidget)
        self.statistic_box.setGeometry(QtCore.QRect(285, 10, 501, 576))
        self.statistic_box.setStyleSheet("font: 10pt \"Arial\";")
        self.statistic_box.setAlignment(QtCore.Qt.AlignCenter)
        self.statistic_box.setObjectName("statistic_box")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.statistic_box)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 25, 466, 27))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setStyleSheet("font: 10pt \"Arial\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setStyleSheet("font: 8pt \"Arial\";")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.statistic_box)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 361, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setStyleSheet("font: 10pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox.setStyleSheet("font: 9pt \"Arial\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setStyleSheet("font: 8pt \"Arial\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.statistic_box)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 100, 351, 61))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_3.setStyleSheet("font: 10pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_3.setStyleSheet("font: 8pt \"Arial\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_2.setStyleSheet("font: 8pt \"Arial\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.statistic_box)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 170, 351, 36))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setStyleSheet("font: 10pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_2.setStyleSheet("font: 8pt \"Arial\";")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton.setStyleSheet("font: 8pt \"Arial\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.statistic_box)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 255, 449, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox_3.setStyleSheet("font: 8pt \"Arial\";")
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_4.addWidget(self.comboBox_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_4.setStyleSheet("font: 8pt \"Arial\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox_5.setStyleSheet("font: 8pt \"Arial\";")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_5)
        self.comboBox_4 = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox_4.setStyleSheet("font: 8pt \"Arial\";")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_4)
        self.information_box = QtWidgets.QGroupBox(ManagementWidget)
        self.information_box.setGeometry(QtCore.QRect(10, 10, 251, 541))
        self.information_box.setStyleSheet("font: 10pt \"Arial\";")
        self.information_box.setAlignment(QtCore.Qt.AlignCenter)
        self.information_box.setObjectName("information_box")
        self.show_or_hide = QtWidgets.QPushButton(self.information_box)
        self.show_or_hide.setGeometry(QtCore.QRect(15, 30, 221, 31))
        self.show_or_hide.setStyleSheet("font: 10pt \"Arial\";")
        self.show_or_hide.setObjectName("show_or_hide")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.information_box)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(15, 72, 219, 173))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.bot_information_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.bot_information_layout.setContentsMargins(0, 0, 0, 0)
        self.bot_information_layout.setObjectName("bot_information_layout")
        self.top_layout = QtWidgets.QGridLayout()
        self.top_layout.setObjectName("top_layout")
        self.top_show_or_hide = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.top_show_or_hide.setMaximumSize(QtCore.QSize(26, 26))
        self.top_show_or_hide.setText("")
        self.top_show_or_hide.setObjectName("top_show_or_hide")
        self.top_layout.addWidget(self.top_show_or_hide, 1, 2, 1, 1)
        self.top_name_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.top_name_line.setText("")
        self.top_name_line.setDragEnabled(False)
        self.top_name_line.setReadOnly(True)
        self.top_name_line.setObjectName("top_name_line")
        self.top_layout.addWidget(self.top_name_line, 1, 1, 1, 1)
        self.top_name_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.top_name_label.setStyleSheet("font: 10pt \"Arial\";")
        self.top_name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.top_name_label.setObjectName("top_name_label")
        self.top_layout.addWidget(self.top_name_label, 0, 1, 1, 1)
        self.bot_information_layout.addLayout(self.top_layout)
        self.middle_layout = QtWidgets.QGridLayout()
        self.middle_layout.setObjectName("middle_layout")
        self.middle_token_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.middle_token_line.setReadOnly(True)
        self.middle_token_line.setObjectName("middle_token_line")
        self.middle_layout.addWidget(self.middle_token_line, 1, 0, 1, 1)
        self.middle_show_or_hide = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.middle_show_or_hide.setMaximumSize(QtCore.QSize(26, 26))
        self.middle_show_or_hide.setText("")
        self.middle_show_or_hide.setObjectName("middle_show_or_hide")
        self.middle_layout.addWidget(self.middle_show_or_hide, 1, 1, 1, 1)
        self.middle_token_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.middle_token_label.setStyleSheet("font: 10pt \"Arial\";")
        self.middle_token_label.setObjectName("middle_token_label")
        self.middle_layout.addWidget(self.middle_token_label, 0, 0, 1, 1)
        self.bot_information_layout.addLayout(self.middle_layout)
        self.bottom_layout = QtWidgets.QGridLayout()
        self.bottom_layout.setObjectName("bottom_layout")
        self.bottom_show_or_hide = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.bottom_show_or_hide.setMaximumSize(QtCore.QSize(26, 26))
        self.bottom_show_or_hide.setText("")
        self.bottom_show_or_hide.setObjectName("bottom_show_or_hide")
        self.bottom_layout.addWidget(self.bottom_show_or_hide, 1, 1, 1, 1)
        self.bottom_cogs_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.bottom_cogs_line.setReadOnly(True)
        self.bottom_cogs_line.setObjectName("bottom_cogs_line")
        self.bottom_layout.addWidget(self.bottom_cogs_line, 1, 0, 1, 1)
        self.bottom_cogs_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.bottom_cogs_label.setStyleSheet("font: 10pt \"Arial\";")
        self.bottom_cogs_label.setObjectName("bottom_cogs_label")
        self.bottom_layout.addWidget(self.bottom_cogs_label, 0, 0, 1, 1)
        self.bot_information_layout.addLayout(self.bottom_layout)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.information_box)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(15, 255, 219, 88))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.cogs_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.cogs_layout.setContentsMargins(0, 0, 0, 0)
        self.cogs_layout.setObjectName("cogs_layout")
        self.cogs_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cogs_label.setMaximumSize(QtCore.QSize(300, 25))
        self.cogs_label.setStyleSheet("font: 10pt \"Arial\";")
        self.cogs_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cogs_label.setObjectName("cogs_label")
        self.cogs_layout.addWidget(self.cogs_label)
        self.management_cogs_layout = QtWidgets.QGridLayout()
        self.management_cogs_layout.setObjectName("management_cogs_layout")
        self.off_cogs = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.off_cogs.setObjectName("off_cogs")
        self.management_cogs_layout.addWidget(self.off_cogs, 3, 2, 1, 1)
        self.disconnect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.disconnect.setStyleSheet("font: 9pt \"Arial\";")
        self.disconnect.setObjectName("disconnect")
        self.management_cogs_layout.addWidget(self.disconnect, 2, 0, 1, 1)
        self.connect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.connect.setStyleSheet("font: 9pt \"Arial\";")
        self.connect.setObjectName("connect")
        self.management_cogs_layout.addWidget(self.connect, 2, 2, 1, 1)
        self.on_cogs = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.on_cogs.setObjectName("on_cogs")
        self.management_cogs_layout.addWidget(self.on_cogs, 3, 0, 1, 1)
        self.cogs_layout.addLayout(self.management_cogs_layout)
        self.exit_button = QtWidgets.QPushButton(ManagementWidget)
        self.exit_button.setGeometry(QtCore.QRect(10, 555, 251, 31))
        self.exit_button.setStyleSheet("font: 10pt \"Arial\";")
        self.exit_button.setObjectName("exit_button")

        self.retranslateUi(ManagementWidget)
        QtCore.QMetaObject.connectSlotsByName(ManagementWidget)

    def retranslateUi(self, ManagementWidget):
        _translate = QtCore.QCoreApplication.translate
        ManagementWidget.setWindowTitle(_translate("ManagementWidget", "Form"))
        self.statistic_box.setTitle(_translate("ManagementWidget", "СТАТИСТИКА"))
        self.label.setText(_translate("ManagementWidget", "Никнейм бота:"))
        self.label_2.setText(_translate("ManagementWidget", "Статус бота:"))
        self.comboBox.setItemText(0, _translate("ManagementWidget", "В сети"))
        self.comboBox.setItemText(1, _translate("ManagementWidget", "Не активный"))
        self.comboBox.setItemText(2, _translate("ManagementWidget", "Не беспокоить"))
        self.comboBox.setItemText(3, _translate("ManagementWidget", "Не в сети"))
        self.pushButton_3.setText(_translate("ManagementWidget", "Обновить"))
        self.label_3.setText(_translate("ManagementWidget", "Пользовательский статус бота:"))
        self.pushButton_2.setText(_translate("ManagementWidget", "Обновить"))
        self.label_4.setText(_translate("ManagementWidget", "Количество серверов:"))
        self.pushButton.setText(_translate("ManagementWidget", "Обновить"))
        self.pushButton_4.setText(_translate("ManagementWidget", "Получить информацию"))
        self.comboBox_5.setItemText(0, _translate("ManagementWidget", "Участники"))
        self.comboBox_5.setItemText(1, _translate("ManagementWidget", "Роли"))
        self.comboBox_5.setItemText(2, _translate("ManagementWidget", "Каналы"))
        self.comboBox_4.setItemText(0, _translate("ManagementWidget", "txt"))
        self.comboBox_4.setItemText(1, _translate("ManagementWidget", "csv"))
        self.comboBox_4.setItemText(2, _translate("ManagementWidget", "sqlite"))
        self.information_box.setTitle(_translate("ManagementWidget", "ИНФОРМАЦИЯ"))
        self.show_or_hide.setText(_translate("ManagementWidget", "Скрыть информацию"))
        self.top_name_label.setText(_translate("ManagementWidget", "Название бота:"))
        self.middle_token_label.setText(_translate("ManagementWidget", "Токен бота:"))
        self.bottom_cogs_label.setText(_translate("ManagementWidget", "Путь к доп. командам:"))
        self.cogs_label.setText(_translate("ManagementWidget", "Комманды:"))
        self.disconnect.setText(_translate("ManagementWidget", "Отключить"))
        self.connect.setText(_translate("ManagementWidget", "Подключить"))
        self.exit_button.setText(_translate("ManagementWidget", "Выйти в меню"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManagementWidget = QtWidgets.QWidget()
    ui = Ui_ManagementWidget()
    ui.setupUi(ManagementWidget)
    ManagementWidget.show()
    sys.exit(app.exec_())
