# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/source/bot_management.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BotManagement(object):
    def setupUi(self, BotManagement):
        BotManagement.setObjectName("BotManagement")
        BotManagement.resize(800, 600)
        self.exit_to_menu_button = QtWidgets.QPushButton(BotManagement)
        self.exit_to_menu_button.setGeometry(QtCore.QRect(12, 557, 271, 31))
        self.exit_to_menu_button.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.exit_to_menu_button.setObjectName("exit_to_menu_button")
        self.statistics_box = QtWidgets.QGroupBox(BotManagement)
        self.statistics_box.setGeometry(QtCore.QRect(295, 9, 491, 581))
        self.statistics_box.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.statistics_box.setAlignment(QtCore.Qt.AlignCenter)
        self.statistics_box.setObjectName("statistics_box")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.statistics_box)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 466, 185))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.statistics_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.statistics_layout.setContentsMargins(0, 0, 0, 0)
        self.statistics_layout.setObjectName("statistics_layout")
        self.nickname_bot_layout = QtWidgets.QHBoxLayout()
        self.nickname_bot_layout.setSpacing(3)
        self.nickname_bot_layout.setObjectName("nickname_bot_layout")
        self.nickname_bot_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nickname_bot_label.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.nickname_bot_label.setObjectName("nickname_bot_label")
        self.nickname_bot_layout.addWidget(self.nickname_bot_label)
        self.nickname_bot = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nickname_bot.setReadOnly(True)
        self.nickname_bot.setObjectName("nickname_bot")
        self.nickname_bot_layout.addWidget(self.nickname_bot)
        self.nickname_bot_update_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nickname_bot_update_button.setMinimumSize(QtCore.QSize(100, 0))
        self.nickname_bot_update_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nickname_bot_update_button.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.nickname_bot_update_button.setObjectName("nickname_bot_update_button")
        self.nickname_bot_layout.addWidget(self.nickname_bot_update_button)
        self.statistics_layout.addLayout(self.nickname_bot_layout)
        self.activity_status_bot_layout = QtWidgets.QHBoxLayout()
        self.activity_status_bot_layout.setSpacing(3)
        self.activity_status_bot_layout.setObjectName("activity_status_bot_layout")
        self.activity_status_bot_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.activity_status_bot_label.setMinimumSize(QtCore.QSize(170, 0))
        self.activity_status_bot_label.setMaximumSize(QtCore.QSize(170, 16777215))
        self.activity_status_bot_label.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.activity_status_bot_label.setObjectName("activity_status_bot_label")
        self.activity_status_bot_layout.addWidget(self.activity_status_bot_label)
        self.activity_status_bot_list = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.activity_status_bot_list.setStyleSheet("")
        self.activity_status_bot_list.setObjectName("activity_status_bot_list")
        self.activity_status_bot_list.addItem("")
        self.activity_status_bot_list.addItem("")
        self.activity_status_bot_list.addItem("")
        self.activity_status_bot_list.addItem("")
        self.activity_status_bot_layout.addWidget(self.activity_status_bot_list)
        self.activity_status_bot_update_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.activity_status_bot_update_button.setMinimumSize(QtCore.QSize(100, 0))
        self.activity_status_bot_update_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.activity_status_bot_update_button.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.activity_status_bot_update_button.setObjectName("activity_status_bot_update_button")
        self.activity_status_bot_layout.addWidget(self.activity_status_bot_update_button)
        self.statistics_layout.addLayout(self.activity_status_bot_layout)
        self.status_bot_layout = QtWidgets.QHBoxLayout()
        self.status_bot_layout.setSpacing(3)
        self.status_bot_layout.setObjectName("status_bot_layout")
        self.status_bot_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.status_bot_label.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.status_bot_label.setObjectName("status_bot_label")
        self.status_bot_layout.addWidget(self.status_bot_label)
        self.status_bot = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.status_bot.setObjectName("status_bot")
        self.status_bot_layout.addWidget(self.status_bot)
        self.status_bot_update_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.status_bot_update_button.setMinimumSize(QtCore.QSize(100, 0))
        self.status_bot_update_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.status_bot_update_button.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.status_bot_update_button.setObjectName("status_bot_update_button")
        self.status_bot_layout.addWidget(self.status_bot_update_button)
        self.statistics_layout.addLayout(self.status_bot_layout)
        self.servers_count_layout = QtWidgets.QHBoxLayout()
        self.servers_count_layout.setSpacing(3)
        self.servers_count_layout.setObjectName("servers_count_layout")
        self.servers_count_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.servers_count_label.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.servers_count_label.setObjectName("servers_count_label")
        self.servers_count_layout.addWidget(self.servers_count_label)
        self.servers_count = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.servers_count.setReadOnly(True)
        self.servers_count.setObjectName("servers_count")
        self.servers_count_layout.addWidget(self.servers_count)
        self.servers_count_update_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.servers_count_update_button.setMinimumSize(QtCore.QSize(100, 0))
        self.servers_count_update_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.servers_count_update_button.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.servers_count_update_button.setObjectName("servers_count_update_button")
        self.servers_count_layout.addWidget(self.servers_count_update_button)
        self.statistics_layout.addLayout(self.servers_count_layout)
        self.users_count_layout = QtWidgets.QHBoxLayout()
        self.users_count_layout.setSpacing(3)
        self.users_count_layout.setObjectName("users_count_layout")
        self.users_count_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.users_count_label.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.users_count_label.setObjectName("users_count_label")
        self.users_count_layout.addWidget(self.users_count_label)
        self.users_count = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.users_count.setReadOnly(True)
        self.users_count.setObjectName("users_count")
        self.users_count_layout.addWidget(self.users_count)
        self.users_count_update_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.users_count_update_button.setMinimumSize(QtCore.QSize(100, 0))
        self.users_count_update_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.users_count_update_button.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.users_count_update_button.setObjectName("users_count_update_button")
        self.users_count_layout.addWidget(self.users_count_update_button)
        self.statistics_layout.addLayout(self.users_count_layout)
        self.information_box = QtWidgets.QGroupBox(BotManagement)
        self.information_box.setGeometry(QtCore.QRect(15, 10, 266, 541))
        self.information_box.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.information_box.setAlignment(QtCore.Qt.AlignCenter)
        self.information_box.setObjectName("information_box")
        self.show_or_hide_information_button = QtWidgets.QPushButton(self.information_box)
        self.show_or_hide_information_button.setGeometry(QtCore.QRect(15, 30, 236, 36))
        self.show_or_hide_information_button.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.show_or_hide_information_button.setObjectName("show_or_hide_information_button")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.information_box)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(15, 75, 236, 56))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.name_bot_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.name_bot_layout.setContentsMargins(0, 0, 0, 0)
        self.name_bot_layout.setSpacing(3)
        self.name_bot_layout.setObjectName("name_bot_layout")
        self.name_bot_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.name_bot_label.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.name_bot_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name_bot_label.setObjectName("name_bot_label")
        self.name_bot_layout.addWidget(self.name_bot_label)
        self.name_bot_line = QtWidgets.QHBoxLayout()
        self.name_bot_line.setSpacing(3)
        self.name_bot_line.setObjectName("name_bot_line")
        self.name_bot = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.name_bot.setMinimumSize(QtCore.QSize(0, 25))
        self.name_bot.setMaximumSize(QtCore.QSize(16777215, 25))
        self.name_bot.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.name_bot.setEchoMode(QtWidgets.QLineEdit.Password)
        self.name_bot.setReadOnly(True)
        self.name_bot.setObjectName("name_bot")
        self.name_bot_line.addWidget(self.name_bot)
        self.show_or_hide_name_bot_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.show_or_hide_name_bot_button.setMinimumSize(QtCore.QSize(25, 25))
        self.show_or_hide_name_bot_button.setMaximumSize(QtCore.QSize(25, 25))
        self.show_or_hide_name_bot_button.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.show_or_hide_name_bot_button.setObjectName("show_or_hide_name_bot_button")
        self.name_bot_line.addWidget(self.show_or_hide_name_bot_button)
        self.name_bot_layout.addLayout(self.name_bot_line)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.information_box)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(15, 135, 236, 56))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.token_bot_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.token_bot_layout.setContentsMargins(0, 0, 0, 0)
        self.token_bot_layout.setSpacing(3)
        self.token_bot_layout.setObjectName("token_bot_layout")
        self.token_bot_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.token_bot_label.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.token_bot_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.token_bot_label.setObjectName("token_bot_label")
        self.token_bot_layout.addWidget(self.token_bot_label)
        self.token_bot_line = QtWidgets.QHBoxLayout()
        self.token_bot_line.setSpacing(3)
        self.token_bot_line.setObjectName("token_bot_line")
        self.token_bot = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.token_bot.setMinimumSize(QtCore.QSize(0, 25))
        self.token_bot.setMaximumSize(QtCore.QSize(16777215, 25))
        self.token_bot.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.token_bot.setEchoMode(QtWidgets.QLineEdit.Password)
        self.token_bot.setReadOnly(True)
        self.token_bot.setObjectName("token_bot")
        self.token_bot_line.addWidget(self.token_bot)
        self.show_or_hide_token_bot_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.show_or_hide_token_bot_button.setMinimumSize(QtCore.QSize(25, 25))
        self.show_or_hide_token_bot_button.setMaximumSize(QtCore.QSize(25, 25))
        self.show_or_hide_token_bot_button.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.show_or_hide_token_bot_button.setObjectName("show_or_hide_token_bot_button")
        self.token_bot_line.addWidget(self.show_or_hide_token_bot_button)
        self.token_bot_layout.addLayout(self.token_bot_line)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.information_box)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(15, 205, 236, 96))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.management_commands_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.management_commands_layout.setContentsMargins(0, 0, 0, 0)
        self.management_commands_layout.setSpacing(4)
        self.management_commands_layout.setObjectName("management_commands_layout")
        self.commands_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.commands_label.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.commands_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.commands_label.setObjectName("commands_label")
        self.management_commands_layout.addWidget(self.commands_label)
        self.commands_layout = QtWidgets.QGridLayout()
        self.commands_layout.setObjectName("commands_layout")
        self.unload_command_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.unload_command_button.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.unload_command_button.setObjectName("unload_command_button")
        self.commands_layout.addWidget(self.unload_command_button, 0, 0, 1, 1)
        self.loaded_commands_list = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.loaded_commands_list.setObjectName("loaded_commands_list")
        self.commands_layout.addWidget(self.loaded_commands_list, 2, 0, 1, 1)
        self.load_command_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.load_command_button.setStyleSheet("font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.load_command_button.setObjectName("load_command_button")
        self.commands_layout.addWidget(self.load_command_button, 0, 1, 1, 1)
        self.unloaded_commands_list = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.unloaded_commands_list.setObjectName("unloaded_commands_list")
        self.commands_layout.addWidget(self.unloaded_commands_list, 2, 1, 1, 1)
        self.management_commands_layout.addLayout(self.commands_layout)

        self.retranslateUi(BotManagement)
        QtCore.QMetaObject.connectSlotsByName(BotManagement)

    def retranslateUi(self, BotManagement):
        _translate = QtCore.QCoreApplication.translate
        BotManagement.setWindowTitle(_translate("BotManagement", "Form"))
        self.exit_to_menu_button.setText(_translate("BotManagement", "Выйти в меню"))
        self.statistics_box.setTitle(_translate("BotManagement", "Статистика"))
        self.nickname_bot_label.setText(_translate("BotManagement", "Никнейм бота:"))
        self.nickname_bot_update_button.setText(_translate("BotManagement", "Обновить"))
        self.activity_status_bot_label.setText(_translate("BotManagement", "Статус активности бота:"))
        self.activity_status_bot_list.setItemText(0, _translate("BotManagement", "В сети"))
        self.activity_status_bot_list.setItemText(1, _translate("BotManagement", "Не активный"))
        self.activity_status_bot_list.setItemText(2, _translate("BotManagement", "Не беспокоить"))
        self.activity_status_bot_list.setItemText(3, _translate("BotManagement", "Не в сети"))
        self.activity_status_bot_update_button.setText(_translate("BotManagement", "Обновить"))
        self.status_bot_label.setText(_translate("BotManagement", "Статус бота:"))
        self.status_bot_update_button.setText(_translate("BotManagement", "Обновить"))
        self.servers_count_label.setText(_translate("BotManagement", "Количество серверов:"))
        self.servers_count_update_button.setText(_translate("BotManagement", "Обновить"))
        self.users_count_label.setText(_translate("BotManagement", "Количество пользователей:"))
        self.users_count_update_button.setText(_translate("BotManagement", "Обновить"))
        self.information_box.setTitle(_translate("BotManagement", "Информация"))
        self.show_or_hide_information_button.setText(_translate("BotManagement", "Скрыть информацию"))
        self.name_bot_label.setText(_translate("BotManagement", "Название бота:"))
        self.show_or_hide_name_bot_button.setText(_translate("BotManagement", "+"))
        self.token_bot_label.setText(_translate("BotManagement", "Токен бота:"))
        self.show_or_hide_token_bot_button.setText(_translate("BotManagement", "+"))
        self.commands_label.setText(_translate("BotManagement", "Команды"))
        self.unload_command_button.setText(_translate("BotManagement", "Отключить"))
        self.load_command_button.setText(_translate("BotManagement", "Подключить"))
